version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: .env
    restart: always

  app:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    ports:
      - "8000:8000"
    command: bash entrypoint.sh
    restart: always
    volumes:
      - .:/app

  redis:
    image: redis:latest
    environment:
       - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --port 6379
    restart: always
