# Generated by Django 4.2.6 on 2024-10-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_search_vector_trigger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_search__98d711_gin',
            old_name='backend_pro_search__22d52f_gin',
        ),
    ]
