# Generated by Django 4.2.6 on 2024-10-09 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_backend_pro_search__22d52f_gin_products_pr_search__98d711_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
    ]
